### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by not-nef**

### CODE REVIEW

**Comment by not-nef** [comment]
This Pull request makes the code smaller, but the difference is not visible! Less Code!!

**Comment by HuyHung1408** [comment]
Ah thank you! I will check it!

**Review by HuyHung1408 — APPROVED** [review]

**Comment by not-nef** [comment]
Great! I will start work on a setup script to build an msi!

**Comment by not-nef** [comment]
should be finished in a few minutes

**Comment by not-nef** [comment]
@HuyHung1408 what will be the next version?

**Comment by HuyHung1408** [comment]
You mean like the version number?

**Comment by not-nef** [comment]
We didnt even have 1.1 yet!

**Comment by not-nef** [comment]
Btw i just realized that i dont have time to do the setup thing rn so it will take a bit

**Comment by HuyHung1408** [comment]
ah ok lol 😂

**Comment by HuyHung1408** [comment]
> Btw i just realized that i dont have time to do the setup thing rn so it will take a bit

dw, that's ok, I also studying for exams rn

**Comment by not-nef** [comment]
@HuyHung1408 The next time you merge a pr, select `Squash and Merge` :)

**Pull request merged**
